[package]
name = "rtz-core"
version = "0.1.5"
edition = "2021"
authors = ["Aaron Roney <twitchax@gmail.com>"]
license = "MIT"
description = "The core functionality for `rtz`."
readme = "../README.md"
homepage = "https://github.com/twitchax/rtz"
repository = "https://github.com/twitchax/rtz"
keywords = ["cli", "time", "zone", "timezone"]
categories = ["command-line-utilities"]

# Allows for us to use wasm and tarpaulin flags.
[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(wasm)', 'cfg(tarpaulin_include)'] }

[features]
default = []
full = ["tz-ned", "tz-osm", "admin-osm", "self-contained"]

double-precision = []
unsimplified = []
extrasimplified = []
self-contained = ["bincode"]

tz-ned = []
tz-osm = []
admin-osm = []

[dependencies]
anyhow = { version = "1.0.72", features = ["backtrace"] }

rayon = "1.7.0"

geojson = "0.24.1"
geo = "0.28.0"

chashmap = "2.2.2"

serde = { version = "1.0.126" }
serde_json = "1.0.64"

# self-contained
bincode = { version = "2.0.0-rc.3", git = "https://github.com/bincode-org/bincode.git", default-features = false, optional = true, features = ["std", "alloc", "serde", "derive"] }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
reqwest = { version = "0.12.5", features = ["blocking"] }
zip = { version = "2.1.6" }

[dev-dependencies]
pretty_assertions = "1.4.0"